services:
  qbittorrent-nordvpn:
    build: .
    container_name: qbittorrent-nordvpn
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "${QBITTORRENT_PORT:-8080}:8080"
      - "6881:6881"
      - "6881:6881/udp"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1